# conf/config.yaml
hydra:
  run:
    dir: ./hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
paths:
  folder_with_pdbs: "../../RFdiffusion/bits2binders_scripts/output_pdbs"
  output_dir: "./outputs"
  path_to_model_weights: ""
  chain_list: "A"

model:
  model_name: "v_48_020"
  use_soluble_model: false
  ca_only: false

run:
  sampling_temps: [0.1, 0.3, 0.5]
  backbone_noises: [0.01, 0.03, 0.05]
  seeds: [42]
  num_seq_per_target: 32
  batch_size: 16
  suppress_print: false
  save_score: false
  max_length: 200000